version: "3.9"

volumes:
  home: {}


services:
  dev-cpp:
    image: nvim-cpp:latest
    container_name: nvim-cpp
    stdin_open: true 
    tty: true 
    volumes:
      - home:/workarea
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
    cap_add:
      - SYS_PTRACE
    restart: always
    security_opt:
      - seccomp:unconfined
    hostname: docker
