apiVersion: apps/v1
kind: Deployment
metadata:
  name: env
  labels:
    app: env
spec:
  replicas: 1
  selector:
    matchLabels:
      name: env
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: env
        app: env
    spec:
      containers:
        - image: clrn/cpp-nvim:latest
          imagePullPolicy: Always
          name: vim
          args: ["nvim"]
          workingDir: /code
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /code
              name: code
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: code
          hostPath:
            path: /home/clrn/git/
        - name: data
          hostPath:
            path: /media/store/cpp-nvim
